<a href="https://colab.research.google.com/github/davidofitaly/Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z-12.5h-/blob/main/01_wprowadzenie/01_array_tablice_numpy_ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1D ARRAY

In [ ]:
import numpy as np

## wersja numpy
np.__version__


'1.21.6'

In [ ]:
##  metody

print(dir())

['In', 'Out', '_', '_2', '_3', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i2', '_i3', '_i4', '_ih', '_ii', '_iii', '_oh', 'exit', 'get_ipython', 'np', 'quit']


In [ ]:
# create array

x = np.array([1,3,5])

x


array([1, 3, 5])

In [ ]:
print(x)

[1 3 5]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# board dimension
x.ndim



1

In [ ]:
# shape dimension
x.shape

(3,)

In [ ]:
# number of elements

x.size

3

In [ ]:
# type 

x.dtype

dtype('int64')

In [ ]:
x = np.array([1.2,4.5,3.4])
print(x)

[1.2 4.5 3.4]


In [ ]:
# type

x.dtype

dtype('float64')

2D ARRAY

In [ ]:
x = np.array([[1,2],[3,5], [3,4]])
print(x)


[[1 2]
 [3 5]
 [3 4]]


In [ ]:
x.shape

(3, 2)

In [ ]:
x.ndim

2

3D ARRAY

In [ ]:
x = np.array([
    [[1,2],
    [2,3]],

    [[8,8],
    [1,9]],

    [[5,7],
     [2,2]]])

print(x)

[[[1 2]
  [2 3]]

 [[8 8]
  [1 9]]

 [[5 7]
  [2 2]]]


In [ ]:
x.ndim

3

In [ ]:
x.shape

(3, 2, 2)