<a href="https://colab.research.google.com/github/davidofitaly/course_notes_data-science-bootcamp-w-j-zyku-python---od-A-do-Z-12.5h-/blob/main/01_wprowadzenie/05_array_generowanie_liczb_pseudolosowych_np_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

GENEROWANIE LICZB PSEUDOLOSOWYCH

In [ ]:
import numpy as np

np.random.seed(0)

In [ ]:
# rozkład normalny 

np.random.randn()

-2.5529898158340787

In [ ]:
np.random.randn(10)

array([ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462, -1.45436567,
        0.04575852, -0.18718385,  1.53277921,  1.46935877,  0.15494743])

In [ ]:
np.random.randn(10,4)

array([[ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656],
       [ 0.3869025 , -0.51080514, -1.18063218, -0.02818223],
       [ 0.42833187,  0.06651722,  0.3024719 , -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628],
       [-1.7262826 ,  0.17742614, -0.40178094, -1.63019835],
       [ 0.46278226, -0.90729836,  0.0519454 ,  0.72909056]])

In [ ]:
# wartosc z przedziału 0-1

np.random.rand()

0.31856895245132366

In [ ]:
np.random.rand(10)

In [ ]:
# zwracanie liczby nieujemnej-losowo

In [ ]:
np.random.randint(10)

0

In [ ]:
np.random.randint(low=10, high=101)

42

In [ ]:
np.random.randint(low=10, high=101, size=5)

array([64, 10, 48, 29, 56])

In [ ]:
# zwracanie losowego elementu z listy

np.random.choice([4,2,4,5,6])

5

In [ ]:
np.random.choice(['sql', 'java', 'python'])


'sql'

In [ ]:
data = np.arange(10)
data


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#shuffle -przetasowanie

np.random.shuffle(data)
data

array([6, 0, 5, 2, 3, 1, 4, 7, 8, 9])