<a href="https://colab.research.google.com/github/davidofitaly/Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z-12.5h-/blob/main/01_wprowadzenie/11_algebra_liniowa_wyznacznik%2C_macierz_jednostkowa%2C_odwrotna_i_transponowana.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

WYZNACZNIK MACIERZY

In [1]:
import numpy as np


In [2]:
# det

A = np.array([[1,2], [3,4]])
np.linalg.det(A)

-2.0000000000000004

ŚLAD MACIERZY


In [6]:
# suma liczb po przekątnej

A = np.array([[2,3], [1,6]])
np.trace(A)


8

MACIERZ JEDNOSTKOWA

In [7]:
# po przekątnej samej 0

np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

MACIERZ ODWROTNA

In [10]:
# macierz odwrotna A *B = B*A = 1

A = np.array([[2,4], [-1,3]])

B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

MACIERZ TRANSPONOWANA

In [12]:
# transpose

np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [13]:
A.T

array([[ 2, -1],
       [ 4,  3]])