<a href="https://colab.research.google.com/github/davidofitaly/Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z-12.5h-/blob/main/01_wprowadzenie/12_algebra_liniowa_rozwi%C4%85zywanie_uk%C5%82ad%C3%B3w_r%C3%B3wna%C5%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ROZWIĄZYWANIE UKŁADÓW RÓWNAŃ

In [3]:
import numpy as np



In [15]:
A = np.array([[2,4], [1,-1]])
B = np.array([[10], [-1]])
print(A)
print()
print(B)


[[ 2  4]
 [ 1 -1]]

[[10]
 [-1]]


In [16]:
A_ivn = np.linalg.inv(A)
A_ivn

array([[ 0.16666667,  0.66666667],
       [ 0.16666667, -0.33333333]])

In [17]:
X = np.dot(A_ivn,B)
X

array([[1.],
       [2.]])