<a href="https://colab.research.google.com/github/davidofitaly/Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z-12.5h-/blob/main/01_wprowadzenie/13_funkcje_statystyczne_w_bibliotece_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

FUNKCJE STATYSTYCZNE

In [3]:
import numpy as np
np.__version__

'1.21.6'

In [6]:
price = np.array([[12.40, 12.80, 11.90, 12.60,1000],
                  [12.50, 13.00, 11.70, 12.20,2000],
                  [12.20, 13.40, 12.20, 13.20,1500]])



In [7]:
# suma wszystkich elemntów
price.sum()

4650.1

In [8]:
# asix=0 suma poszczególnych kolumn

price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [9]:
# asix=1 suma poszczegolnych wierszy

price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

In [11]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [12]:
np.median(price)

12.6

In [13]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [15]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [16]:
np.var(price)

387354.5619555555