<a href="https://colab.research.google.com/github/davidofitaly/Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z-12.5h-/blob/main/02_array_podstawowe_typy_danych_w_bibliotece_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



TYPY DANYCH 


In [49]:
A = np.array([1,2,3])

A.dtype

dtype('int64')

In [51]:
A = np.array([1.1,2.2,3.3,4.4])
A.dtype


dtype('float64')

In [60]:
A = np.array([1,2,3], dtype='float')
A.dtype

A

array([1., 2., 3.])

In [59]:
A = np.array([1.1,2.2], dtype='int')
A.dtype

A

array([1, 2])

In [61]:
A = np.array([1,2,3], dtype='complex')

# complex konwertuje liczbe na liczbe złożoną 

A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [63]:
A = np.array([True, False])

A.dtype

dtype('bool')

In [65]:
A = np.array([24,80,120], dtype=np.int8)

A.dtype

dtype('int8')

In [68]:
A = np.array([10,100,30], dtype=np.uint8)

A.dtype

dtype('uint8')