<a href="https://colab.research.google.com/github/davidofitaly/Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z-12.5h-/blob/main/04_array_podstawowe_operacje_na_tablicach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
A = np.array([1,2,3,4])
B = np.array([9,8,7,6])

In [5]:
A+B

array([10, 10, 10, 10])

In [6]:
A - B

array([-8, -6, -4, -2])

In [7]:
A * B

array([ 9, 16, 21, 24])

In [8]:
A / B

array([0.11111111, 0.25      , 0.42857143, 0.66666667])

In [10]:
A + 3

array([4, 5, 6, 7])

In [11]:
2 * A

array([2, 4, 6, 8])

In [12]:
A + 3*B

array([28, 26, 24, 22])

In [13]:
np.add(A,B)

array([10, 10, 10, 10])

In [15]:
np.subtract(A,B)

array([-8, -6, -4, -2])

In [16]:
np.multiply(A,B)

array([ 9, 16, 21, 24])

In [18]:
np.divide(A,B)

array([0.11111111, 0.25      , 0.42857143, 0.66666667])

In [20]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])

In [21]:
X *Y 

array([[6, 0],
       [2, 0]])

In [22]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [23]:
np.dot(Y,X)

array([[ 6, 18],
       [-5, -3]])

In [24]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [25]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [26]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [27]:
Y @ X

array([[ 6, 18],
       [-5, -3]])