<a href="https://colab.research.google.com/github/davidofitaly/Data-Science-Bootcamp-w-j-zyku-Python---od-A-do-Z-12.5h-/blob/main/07_array_indeksowanie_i_wycinanie_tablic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INDESKOWANIE-WYCINANIE

In [2]:
import numpy as np


In [22]:
A = np.arange(20)

In [ ]:
# A[idx], A[start:], A[start:stop], A[:stop]

In [23]:
A[5]

5

In [24]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
A[:2]

array([0, 1])

In [26]:
A[[0,1,2,5]]

array([0, 1, 2, 5])

In [27]:
A[-1]

19

In [29]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
A[1]

array([5, 6, 7, 8, 9])

In [33]:
A[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
A[:,2]

array([ 2,  7, 12, 17])

In [35]:
A[1,1:3]

array([6, 7])

In [37]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14, 14,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])